export const FETCH_CARDS = "FETCH_CARDS";

export const REMOVE_SELECTED_CARDS = "REMOVE_SELECTED_CARDS";

export const ADD_CARD_TO_LIST = "ADD_CARD_TO_LIST";

export const SELECT_CARD_HANDLER = "SELECT_CARD_HANDLER";

export const UPDATE_CARD_HANDLER = "UPDATE_CARD_HANDLER";

export const SWITCH_READ_ONLY = "SWITCH_READ_ONLY";